# -- Main menu (header) --

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10
  [main.params]
    groupe = "tech"

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 20
  [main.params]
    groupe = "tech"

[[main]]
  name = "About"
  pageRef = "about"
  weight = 5

[[main]]
  name = "Jazz"
  pageRef = "jazz"
  pre = "music"
  weight = 50
  [main.params]
    groupe = "loisirs"

[[main]]
  name = "Migration"
  pageRef = "migration"
  pre = "globe"
  weight = 60
  [main.params]
    groupe = "loisirs"

[[main]]
  name = "Resume"
  pageRef = "cv"
  weight = 7

# -- Footer menu --

[[footer]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[footer]]
  name = "Projects"
  pageRef = "projects"
  weight = 20

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 30

[[footer]]
  name = "Jazz"
  pageRef = "jazz"
  weight = 25

[[footer]]
  name = "Migration"
  pageRef = "migration"
  weight = 27
